"""create field chat_id in  chat_history table

Revision ID: da917eb6000f
Revises: 207aec12d646
Create Date: 2025-06-25 06:07:12.210852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da917eb6000f'
down_revision: Union[str, None] = '207aec12d646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chathistorys', sa.Column('session_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chathistorys', 'session_id')
    # ### end Alembic commands ###
